// Keeps the public showroom site's per-line stock numbers in sync with real
// Turso inventory. This only ever touches ONE small file — inventory-data.js
// — in the showroom's GitHub repo. It never touches the big photo-laden HTML
// files themselves, so this stays fast, cheap, and can't ever corrupt the
// embedded photos no matter how often it runs.
//
// Each showroom line page (120/121/140/141/142) already has its own
// INVENTORY_<model> object baked in as a fallback; at page load it prefers
// window.LIVE_INVENTORY[model] from inventory-data.js if present, so a sync
// outage (bad token, GitHub down, not configured yet) never breaks the site
// — it just quietly falls back to whatever numbers were last baked in.
//
// 151 is intentionally excluded — that line is custom-order-only and was
// never inventory-tracked on the showroom (Dawson's explicit call).

import { db } from './db.js';

const TRACKED_MODELS = ['120', '121', '140', '141', '142'];

// Showroom color code -> the lowercase key each showroom page's
// INVENTORY_<model> object actually uses (verified against the real files —
// note LG shows up as "grey", not "light grey").
const COLOR_KEY = { WE: 'white', BK: 'black', BE: 'beige', LG: 'grey', KH: 'khaki', TA: 'tan', BL: 'blue', BU: 'blue', OR: 'orange' };

// Ops-app piece label -> the short key each showroom page's per-piece counts
// object uses. Anything not listed here (e.g. the UNCONFIRMED 143/151 labels)
// is deliberately skipped rather than guessed.
const PIECE_KEY = {
  'Left-facing': 'left',
  'Right-facing': 'right',
  'Middle': 'middle',
  'Ottoman': 'ottoman',
  'Wedge': 'wedge',
  'Corner (reversible)': 'corner',
};

/** Real per-model, per-color, per-piece box counts (Dawson + Grant combined), for the 5 showroom-tracked lines only. */
export async function buildLiveInventory() {
  const live = {};
  for (const model of TRACKED_MODELS) {
    const products = await db.all(`SELECT * FROM products WHERE model = ? AND active = 1`, [model]);
    const modelData = {};
    for (const p of products) {
      const colorKey = COLOR_KEY[p.color];
      if (!colorKey) continue; // unrecognized color code — skip rather than guess
      const pieces = await db.all(`SELECT id, label FROM piece_types WHERE product_id = ?`, [p.id]);
      const counts = {};
      for (const pt of pieces) {
        const key = PIECE_KEY[pt.label];
        if (!key) continue; // unconfirmed/unusual piece label — skip rather than guess
        const row = await db.get(`SELECT COALESCE(SUM(quantity),0) s FROM inventory WHERE piece_type_id = ?`, [pt.id]);
        counts[key] = (counts[key] || 0) + row.s;
      }
      modelData[colorKey] = counts;
    }
    live[model] = modelData;
  }
  return live;
}

function toJsSource(live) {
  return `// Auto-generated by the ops app's showroom sync — do not edit by hand.\n` +
    `// Reflects real Turso inventory as of the timestamp below.\n` +
    `window.LIVE_INVENTORY = ${JSON.stringify(live, null, 2)};\n` +
    `window.LIVE_INVENTORY_SYNCED_AT = ${JSON.stringify(new Date().toISOString())};\n`;
}

let lastSyncAt = 0;
let lastSyncResult = null;

export function getLastSyncStatus() {
  return { lastSyncAt, lastSyncResult };
}

/** Pushes current inventory to the showroom repo's inventory-data.js via GitHub's Contents API (one small file, one commit). */
export async function syncShowroomInventory() {
  const repo = process.env.SHOWROOM_GITHUB_REPO;    // e.g. "yourusername/redefined-couches-showroom"
  const token = process.env.SHOWROOM_GITHUB_TOKEN;  // a GitHub fine-grained PAT, Contents: read/write on that one repo
  const branch = process.env.SHOWROOM_GITHUB_BRANCH || 'main';
  const path = 'inventory-data.js';

  if (!repo || !token) {
    const result = { ok: false, detail: 'Not configured yet — set SHOWROOM_GITHUB_REPO and SHOWROOM_GITHUB_TOKEN in Render’s environment variables.' };
    lastSyncAt = Date.now();
    lastSyncResult = result;
    return result;
  }

  try {
    const live = await buildLiveInventory();
    const content = toJsSource(live);
    const apiBase = `https://api.github.com/repos/${repo}/contents/${path}`;
    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'User-Agent': 'redefined-couches-ops-app',
    };

    // Need the current file's sha to update it — GitHub requires this so two
    // concurrent writers can't silently clobber each other.
    let sha;
    const getRes = await fetch(`${apiBase}?ref=${branch}`, { headers });
    if (getRes.status === 200) {
      sha = (await getRes.json()).sha;
    } else if (getRes.status !== 404) {
      throw new Error(`couldn't read current file (HTTP ${getRes.status})`);
    }

    const putRes = await fetch(apiBase, {
      method: 'PUT',
      headers: { ...headers, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: 'Auto-sync: update showroom stock from ops app',
        content: Buffer.from(content, 'utf8').toString('base64'),
        branch,
        ...(sha ? { sha } : {}),
      }),
    });

    if (putRes.status === 200 || putRes.status === 201) {
      const colorCount = Object.values(live).reduce((n, m) => n + Object.keys(m).length, 0);
      const result = { ok: true, detail: `Synced ${colorCount} product colors across ${TRACKED_MODELS.length} lines.` };
      lastSyncAt = Date.now();
      lastSyncResult = result;
      return result;
    }
    const body = await putRes.text();
    throw new Error(`GitHub rejected the update (HTTP ${putRes.status}): ${body.slice(0, 200)}`);
  } catch (err) {
    const result = { ok: false, detail: err.message };
    lastSyncAt = Date.now();
    lastSyncResult = result;
    return result;
  }
}
